# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - development
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)/EmbededShell/EmbeddedbiShell/SampleCoreApp.csproj'
    arguments: '--output "$(Build.SourcesDirectory)/output/adhoc" --configuration Release'
    zipAfterPublish: false
    modifyOutputPath: false
- task: Docker@2
  inputs:
    containerRegistry: 'Push Image to Artifact Registry'
    repository: 'boldbi-dev-296107/boldbik8s/boldbi-adhoc-embed'
    command: 'build'
    Dockerfile: 'webapp.Dockerfile'
    tags: '5.3.ad$(Build.BuildId)'
  displayName: Docker Build Image
- task: Docker@2
  inputs:
    containerRegistry: 'Push Image to Artifact Registry'
    repository: 'boldbi-dev-296107/boldbik8s/boldbi-adhoc-embed'
    command: 'push'
    tags: '5.3.ad$(Build.BuildId)'
  displayName: Docker push Image
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '(Get-Content deployment/deployment.yaml).replace(''#ImageUrl#'', ''5.3.ad$(Build.BuildId)'') | Set-Content deployment/deployment.yaml'
  displayName: Replace Tag in dataservice deployment file
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/deployment/deployment.yaml'
    artifact: 'manifest'
    publishLocation: 'pipeline'
  displayName: move the tag replaced deployment file to Release pipeline


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
